# # Use the official PostgreSQL base image
# FROM postgres:latest

# LABEL "Project"="Apex_Network"
# LABEL "Author"="Tejiri"
# # Add custom configuration file to the image
# COPY custom-postgresql.conf /etc/postgresql/postgresql.conf

# # Run initialization scripts (e.g., creating databases, users)
# COPY init.sql /docker-entrypoint-initdb.d/

# # Set environment variables if needed
# ENV POSTGRES_USER=apex_db
# ENV POSTGRES_PASSWORD=G7ujfQtnUhh1LpuoXKL5KDbovSp8CS4N
# ENV POSTGRES_DB=apex_db_bpnc

# # Expose the PostgreSQL port
# EXPOSE 3000
