pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'  // ID of your Docker Hub credentials in Jenkins
        DOCKER_IMAGE = 'oluty/apexapp'
        GIT_REPO = 'https://github.com/Oluty-1/apex-network_mod.git'
        BRANCH = 'main'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: "${main}", url: "${GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    def customImage = docker.build("${DOCKER_IMAGE}")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Login to Docker Hub
                    docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_CREDENTIALS_ID}") {
                        // Push the Docker image
                        customImage.push("${BRANCH}")
                    }
                }
            }
        }

        stage('Clean up') {
            steps {
                // Clean up the Docker environment
                sh "docker rmi ${DOCKER_IMAGE}:${BRANCH}"
            }
        }
    }

    post {
        always {
            // Notify in case of failure/success
            echo 'Pipeline finished!'
        }
        cleanup {
            // Cleanup the workspace
            deleteDir()
        }
    }
}
